jbosstm/performance

- narayana/tools/src/main/java/io/narayana/perf/jmh/BMParser.java
> [JBTM-2368] parse ints as Double and then convert to int

- narayana/scripts/hudson/hw.sh
> JBTM-2369 OS X script for collecting hw info

- comparison/pom.xml
- narayana/ArjunaCore/arjuna/pom.xml
- narayana/ArjunaJTA/jta/pom.xml
- narayana/pom.xml
- narayana/tools/pom.xml
- product/pom.xml
> JBTM-2466 Depend on current narayana master version

- narayana/ArjunaJTA/jta/pom.xml
https://issues.jboss.org/browse/JBTM-2494
> JBTM-2494 Add dependency on artemis journal

- narayana/ArjunaJTA/jta/pom.xml
- narayana/ArjunaJTA/jta/tests/classes/io/narayana/perf/product/ProductComparison.java
- narayana/ArjunaJTA/jta/tests/classes/io/narayana/perf/product/ProductInterface.java
- narayana/ArjunaJTA/jta/tests/classes/io/narayana/perf/product/ProductWorker.java
https://issues.jboss.org/browse/JBTM-395
> JBTM-395 Add geronimo to the prod coparison matrix

- comparison/common/pom.xml
- comparison/common/src/main/java/org/jboss/narayana/performance/common/test/AbstractTestCase.java
- comparison/jts/src/test/java/org/jboss/narayana/jts/TestCase.java
- comparison/pom.xml
https://issues.jboss.org/browse/JBTM-2468
> [JBTM-2468] Update to use iiop-openjdk subsystem

- narayana/ArjunaJTA/jta/tests/classes/io/narayana/perf/product/AtomikosComparison.java
- narayana/ArjunaJTA/jta/tests/classes/io/narayana/perf/product/BitronixComparison.java
- narayana/ArjunaJTA/jta/tests/classes/io/narayana/perf/product/GeronimoComparison.java
- narayana/ArjunaJTA/jta/tests/classes/io/narayana/perf/product/JotmComparison.java
- narayana/ArjunaJTA/jta/tests/classes/io/narayana/perf/product/NarayanaComparison.java
- narayana/ArjunaJTA/jta/tests/classes/io/narayana/perf/product/ProductComparison.java
- narayana/ArjunaJTA/jta/tests/classes/io/narayana/perf/product/ProductWorker.java
- narayana/scripts/hudson/benchmark.sh
https://issues.jboss.org/browse/JBTM-2538
This PR relates to comparison of different OS TMs. I have separated each test into different class files to ensure that they do not interfere with each other.
> JBTM-2538 Isolate product tests from each other

- narayana/ArjunaJTA/jta/etc/atomikos.properties
- narayana/ArjunaJTA/jta/pom.xml
- narayana/ArjunaJTA/jta/tests/classes/io/narayana/perf/product/AomikosXAResource.java
- narayana/ArjunaJTA/jta/tests/classes/io/narayana/perf/product/AtomikosComparison.java
- narayana/ArjunaJTA/jta/tests/classes/io/narayana/perf/product/BitronixComparison.java
- narayana/ArjunaJTA/jta/tests/classes/io/narayana/perf/product/GeronimoComparison.java
- narayana/ArjunaJTA/jta/tests/classes/io/narayana/perf/product/JotmComparison.java
- narayana/ArjunaJTA/jta/tests/classes/io/narayana/perf/product/NarayanaComparison.java
- narayana/ArjunaJTA/jta/tests/classes/io/narayana/perf/product/ProductComparison.java
- narayana/ArjunaJTA/jta/tests/classes/io/narayana/perf/product/ProductInterface.java
- narayana/ArjunaJTA/jta/tests/classes/io/narayana/perf/product/ProductWorker.java
- narayana/scripts/hudson/benchmark.sh
https://issues.jboss.org/browse/JBTM-2538
The primary fix addressed Atomikos failure due to the max no of transactions being throttled to the default due to the atomikos config file not being found. However, I also need to ensure that atomikos logs are cleaned so I made some other changes as well.
> JBTM-2538 Ensure atomikos config file is accessible

- narayana/scripts/hudson/benchmark.sh
https://issues.jboss.org/browse/JBTM-2538
> JBTM-2538 Run each product benchmark seperately

- narayana/ArjunaJTA/jta/pom.xml
- narayana/scripts/hudson/benchmark.sh
https://issues.jboss.org/browse/JBTM-2555
> JBTM-2555 re-enable JOTM

- narayana/scripts/hudson/benchmark.sh
https://issues.jboss.org/browse/JBTM-2517
A couple of changes to improve error reporting
> JBTM-2517 remember return values

- narayana/ArjunaJTA/jta/tests/classes/io/narayana/perf/product/GenerateReport.java
https://issues.jboss.org/browse/JBTM-2517
JMH output lines are different on my laptop and CI slave so I have changed the regex for matching them.
> JBTM-2517 Update regex for matching JMH output lines

- narayana/ArjunaCore/arjuna/pom.xml
- narayana/ArjunaJTA/jta/pom.xml
- narayana/ArjunaJTS/jts/pom.xml
- narayana/ArjunaJTS/jts/src/test/java/com/hp/mwtests/ts/jts/orbspecific/local/performance/Performance1.java
- narayana/ArjunaJTS/jts/src/test/java/com/hp/mwtests/ts/jts/orbspecific/local/performance/Performance2.java
- narayana/ArjunaJTS/jts/src/test/java/com/hp/mwtests/ts/jts/orbspecific/local/performance/Performance3.java
- narayana/ArjunaJTS/jts/src/test/java/com/hp/mwtests/ts/jts/orbspecific/local/performance/PerformanceWorkerLifecycle.java
- narayana/ArjunaJTS/jts/src/test/resources/jbossts-properties.xml
- narayana/ArjunaJTS/jts/src/test/resources/log4j.xml
- narayana/pom.xml
- narayana/tools/pom.xml
- narayana/tools/src/main/java/io/narayana/perf/Averager.java
- narayana/tools/src/main/java/io/narayana/perf/Measurement.java
- narayana/tools/src/main/java/io/narayana/perf/PerformanceProfileStore.java
- narayana/tools/src/main/java/io/narayana/perf/RegressionChecker.java
- narayana/tools/src/main/java/io/narayana/perf/Worker.java
- narayana/tools/src/main/java/io/narayana/perf/WorkerLifecycle.java
- narayana/tools/src/main/java/io/narayana/perf/WorkerWorkload.java
https://issues.jboss.org/browse/JBTM-2234
> JBTM-2234 Moved to performance repo so we can control the warning level

- narayana/scripts/hudson/jenkins.sh
https://issues.jboss.org/browse/JBTM-2762
> JBTM-2762 Specify the branch to push on

- comparison/pom.xml
- integration/ejb/perftest/perf-eap5/client/pom.xml
- integration/ejb/perftest/perf-eap5/pom.xml
- narayana/ArjunaJTA/jta/pom.xml
- narayana/pom.xml
- product/pom.xml
- tools/download-maven.sh
https://issues.jboss.org/browse/JBTM-3136
fix for CI failure http://narayanaci1.eng.hst.ams2.redhat.com/job/narayana-performance/105/consoleFull
> JBTM-3142 JBTM-3136 do not use https for dependencies

- narayana/scripts/hudson/benchmark.sh
- scripts/run_bm.sh
@mmusgrov I am going to see if increasing the run time reduces the volatility of the result
> increase run time

- narayana/ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/atomicaction/CheckedActionTest.java
- narayana/ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/performance/Performance1.java
- narayana/ArjunaJTA/jta/etc/jotm.properties
- narayana/ArjunaJTA/jta/tests/classes/com/arjuna/ats/jta/xa/performance/HQStoreBenchmark.java
- narayana/ArjunaJTA/jta/tests/classes/com/arjuna/ats/jta/xa/performance/JDBCStoreBenchmark.java
- narayana/ArjunaJTA/jta/tests/classes/com/arjuna/ats/jta/xa/performance/ShadowNoFileLockStoreBenchmark.java
- narayana/ArjunaJTA/jta/tests/classes/com/arjuna/ats/jta/xa/performance/VolatileStoreBenchmark.java
- narayana/ArjunaJTA/jta/tests/classes/org/jboss/narayana/rts/EmptyTxnTest.java
- narayana/ArjunaJTA/jta/tests/classes/org/jboss/narayana/rts/NoTxnTest.java
- narayana/ArjunaJTA/jta/tests/classes/org/jboss/narayana/rts/TxnTest.java
- narayana/scripts/hudson/bm.sh
- narayana/scripts/hudson/jenkins.sh
https://issues.redhat.com/browse/JBTM-3137
> JBTM-3137 Too much variance in the performance PR checker

- scripts/run_bm.sh
https://issues.redhat.com/browse/JBTM-2419
> JBTM-2419 -> Consider reducing the number of JMH perf test forks on PRs

- narayana/ArjunaCore/arjuna/pom.xml
- narayana/ArjunaJTA/jta/pom.xml
- narayana/ArjunaJTA/jta/tests/classes/io/narayana/perf/product/ProductComparison.java
- narayana/pom.xml
https://issues.redhat.com/browse/JBTM-3311
Build failure can be ignored, since it is tracked by https://issues.redhat.com/browse/JBTM-3304
> JBTM-3311: JMH upgrade and code refactor

- scripts/hudson/jenkins.sh
FYI @mayankkunwar @mmusgrov I am going to merge this
> CI SCRIPT ONLY: Pass in the thread counts to the jenkins.sh

- narayana/scripts/hudson/benchmark.sh
- narayana/tools/pom.xml
- narayana/tools/src/main/java/io/narayana/perf/jmh/CsvToJsonConverter.java
https://issues.redhat.com/browse/JBTM-3362
> JBTM-3362 : Produce JSON output from JMH perf runs

- narayana/ArjunaJTA/jta/pom.xml
- narayana/ArjunaJTA/jta/tests/classes/io/narayana/perf/product/AomikosXAResource2.java
- narayana/ArjunaJTA/jta/tests/classes/io/narayana/perf/product/AtomikosComparison.java
https://issues.redhat.com/browse/JBTM-3365
> Update perf competitor open source TM dependencies version to the latest

- comparison/pom.xml
- integration/ejb/perftest/perf-eap5/pom.xml
- integration/jts/application-component-1/pom.xml
- narayana/ArjunaJTA/jta/pom.xml
- narayana/pom.xml
- product/pom.xml
Bring the version of ant up to date.
> upgrade ant version

- comparison/pom.xml
- narayana/ArjunaJTA/jta/pom.xml
https://issues.redhat.com/browse/JBTM-3497
> JBTM-3497 upgrade resteasy client

- comparison/pom.xml
- narayana/ArjunaJTA/jta/pom.xml
Hopefully it could help with CVE-2020-25633
> Align with the version of RESTEasy in WFLY

- narayana/ArjunaJTA/jta/pom.xml
- narayana/pom.xml
- product/pom.xml
https://issues.redhat.com/browse/JBTM-3529
This PR follows up on https://github.com/jbosstm/narayana/pull/1896
> JBTM-3529 Upgrade the activemq artemis dependency

- comparison/common/pom.xml
- comparison/pom.xml
- narayana/ArjunaJTA/jta/pom.xml
- narayana/ArjunaJTA/jta/tests/classes/org/jboss/narayana/rts/JAXRSServer.java
- narayana/ArjunaJTA/jta/tests/classes/org/jboss/narayana/rts/TransactionAwareResource.java
- narayana/pom.xml
- product/pom.xml
- product/src/main/java/com/arjuna/ats/tools/perftest/common/DbWrapper.java
- product/src/main/java/com/arjuna/ats/tools/perftest/common/TestRunner.java
- product/src/main/java/com/arjuna/ats/tools/perftest/product/Product.java
- product/src/test/java/com/arjuna/ats/tools/perftest/task/ProductPerformanceTest.java
https://issues.redhat.com/browse/JBTM-3642
Update jaxb-api version
Update resteasy version
Update netty version
Product :
test (ProductPerformanceTest) does not work: disabling it waiting for ([JBTM-3640](https://issues.redhat.com/browse/JBTM-3640) issue) about Jacorb and JDK 11
use log4j2
> JBTM-3642 Update performance repo dependencies

- narayana/ArjunaJTA/jta/etc/atomikos.properties
- narayana/ArjunaJTA/jta/etc/jbossts-properties.xml
https://issues.redhat.com/browse/JBTM-3757
Narayana "HornetqJournalEnvironmentBean.bufferFlushesPerSecond" property increased. Atomikos "com.atomikos.icatch.max_actives" property set to illimitate.
> [JBTM-3757] Improve Narayana and other products' configuration

- narayana/README.md
- narayana/scripts/hudson/jenkins.sh
- narayana/tools/src/main/java/io/narayana/perf/jmh/Benchmark.java
- scripts/hudson/jenkins.sh
- scripts/run_bm.sh
change 'master' branch reference with 'main' branch
> [JBTM-3718] Conscious Language

- comparison/pom.xml
- narayana/ArjunaCore/arjuna/pom.xml
- narayana/ArjunaJTA/jta/pom.xml
- narayana/ArjunaJTS/jts/pom.xml
- narayana/pom.xml
- narayana/tools/pom.xml
https://issues.redhat.com/browse/JBTM-3779
Move out the test artifacts in narayana-bom
depends on PR https://github.com/jbosstm/narayana/pull/2138
depends on PR https://github.com/jbosstm/performance/pull/167
> JBTM-3779: Move out the test artifacts in narayana-bom #2138

- narayana/ArjunaJTA/jta/pom.xml
https://issues.redhat.com/browse/JBTM-3814
And there is some discussion of the issue on pr #170
> JBTM-3814 H2 dependency should have runtime scope

- narayana/ArjunaJTA/jta/tests/classes/com/arjuna/ats/jta/xa/performance/HQStoreBenchmark.java
- narayana/ArjunaJTA/jta/tests/classes/com/arjuna/ats/jta/xa/performance/JDBCStoreBenchmark.java
- narayana/ArjunaJTA/jta/tests/classes/com/arjuna/ats/jta/xa/performance/JTAStoreBase.java
- narayana/ArjunaJTA/jta/tests/classes/com/arjuna/ats/jta/xa/performance/JTAStoreTests.java
- narayana/ArjunaJTA/jta/tests/classes/com/arjuna/ats/jta/xa/performance/ShadowNoFileLockStoreBenchmark.java
- narayana/ArjunaJTA/jta/tests/classes/com/arjuna/ats/jta/xa/performance/VolatileStoreBenchmark.java
- narayana/scripts/hudson/jenkins.sh
https://issues.redhat.com/browse/JBTM-3815
This PR adds the following feature: "Unexpected performance benchmark exceptions should fail fast"
> Jbtm 3815 Unexpected performance benchmark exceptions should fail fast

- narayana/scripts/hudson/jenkins.sh
@jmfinelli This is a script only change so I don't think we need to run the pull job so I think we can just merge it.
> script change to check for existence of the linux host command

- narayana/ArjunaJTA/jta/pom.xml
- narayana/ArjunaJTA/jta/tests/classes/io/narayana/perf/product/AomikosXAResource.java
- narayana/ArjunaJTA/jta/tests/classes/io/narayana/perf/product/AomikosXAResource2.java
Upgrading Atomikos in order to have updated comparisons with Narayana.
> Bump Atomikos dependencies

- narayana/scripts/hudson/jenkins.sh
Results are generated elsewhere.
artifacts is a private repository now.
> Removing publishing option
